# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title : mfX group
tagline: Multiscale modelling of flows, from the nano- to macro-scales
institute:
  url: https://www.eng.ed.ac.uk/research/institutes/imt
  name: Institute of Multiscale Thermofluids
university:
  url: https://www.ed.ac.uk/
  name: University of Edinburgh
author :
  name : Multiscale Flow X
  email : multiscaleflowx@gmail.com
  github : multiscaleflowx
  twitter : multiscaleflowx

  # The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
# Need to purchase domain
# production_url : multiscaleflowx

# Build settings
markdown: kramdown
url: http://multiscaleflowx.io
permalink: /:categories/:title/
theme: minima
plugins:
  - jekyll-feed

collections:
  project-rarefied:
      output: true
      permalink: /research/project-rarefied/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
