title : mfX group
tagline: Multiscale modelling of flows, from the nano- to macro-scales
institute:
  url: https://www.eng.ed.ac.uk/research/institutes/imt
  name: Institute of Multiscale Thermofluids
university:
  url: https://www.ed.ac.uk/
  name: University of Edinburgh
author :
  name : Multiscale Flow X
  email : multiscaleflowx@gmail.com
  github : multiscaleflowx
  twitter : multiscaleflowx

# Build settings
markdown: kramdown
permalink: /:categories/:title/
theme: minima
plugins:
  - jekyll-feed

# Collection of collections
collections:
  theme-nucleation-phase-change:
      output: true
      permalink: /research/theme-nucleation-phase-change/
  theme-interfacial-phenomena:
    output: true
    permalink: /research/theme-interfacial-phenomena/
  theme-porous-media-flows:
    output: true
    permalink: /research/theme-porous-media-flows/
  theme-particulate-systems:
    output: true
    permalink: /research/theme-particulate-systems/
  contribution-guide:
    output: true
    permalink: /guide/:title

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
